service: lambda-schedule-event

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 10
  logRetentionInDays: 3

functions:
  cron:
    handler: handler.main
    events:
      # NOTE: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
      - schedule: rate(1 minute)
